# Generated by Django 4.2.30 on 2026-04-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
