# Generated by Django 4.2.30 on 2026-04-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
